version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
#  postgres-order:
#    container_name: postgres-order
#    image: postgres
#    environment:
#      POSTGRES_DB: order-service
#      POSTGRES_USER: ptechie
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - ./postgres-order:/data/postgres
#    expose:
#      - "5431"
#    ports:
#      - "5431:5431"
#    command: -p 5431
#    restart: always