version: '3.8'
services:
  mongo_db:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
  mysql_order:
    image: mysql:latest
    container_name: mysql_order
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order-service
    ports:
      - "3306:3306"
  mysql_inventory:
    image: mysql:latest
    container_name: mysql_inventory
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory-service
    ports:
      - "3307:3306"