version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
  db-order-service:
    image: mysql:latest
    container_name: mysql_db_order_service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order-service
    ports:
      - "3306:3306"
  db-inventory-service:
    image: mysql:latest
    container_name: mysql_db_inventory_service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory-service
    ports:
      - "3307:3306"